### ISSUE TITLE
Quill.js 强大优雅的富文本编辑器介绍

### ISSUE THREAD

**Issue by dolphin836** [dolphin836/Blog#5]
![Quill.js](https://github.com/dolphin836/Blog/blob/master/image/quill.jpg?raw=true)

[官网](https://quilljs.com/ "官网")

[Github 主页](https://github.com/quilljs/quill "Github 主页")

[Demo](https://quilljs.com/playground/ "Demo")

[文档](https://quilljs.com/docs/quickstart/ "文档")

在 `Github` 上搜索编辑器的时候发现了 `Quill.js` 这个项目，简单的浏览了它的官网，第一感觉就是文档写的非常好。

立马动手按照文档写了一个简单的 `Demo`，对于一个编辑器我主要关心以下几点：

- UI 颜值既正义
- 自定义功能
- 扩展性

我验证了以下几个常见的需求：

- 个性化工具栏
- 图片上传
- 撤销重做

官网文档都详细介绍了这三个需求的实现方式。

下面是我的 `Demo`，需要注意的是 撤销/重做 是通过 `history` 这个 `module` 实现的。

在 `toolbarOptions` 中添加了 `undo` 和 `redo` 选项，然后通过 `Quill` 提供的 `className` 设置它们的样式，我直接给它们设置了一个背景图片。

HTML

```html
    <div id="quill" class="quill"></div>

    <button id="release">发布</button>

    <input type="file" id="file" style="display:none;" multiple>
```

CSS

```css
.quill {
	height: 375px;
}
.ql-toolbar .ql-formats .ql-undo {
	background: url(./dist/image/undo.svg) no-repeat;
	background-size: 18px 18px;
	background-position: 3px 3px;
}
.ql-toolbar .ql-formats .ql-redo {
	background: url(./dist/image/redo.svg) no-repeat;
	background-size: 18px 18px;
	background-position: 3px 3px;
}
```

JS

```javascript
var toolbarOptions = [
	[{ 'header': 1 }],
	[{ 'header': 2 }],
	['bold'],
	['italic'],
	['underline'],
	['strike'],
	['blockquote'],
	[{ 'list': 'ordered'}],
	[{ 'list': 'bullet' }],
	[{ 'indent': '-1'}],
	[{ 'indent': '+1' }],
	[{ 'color': [] }],
	[{ 'align': [] }],
	['link'],
	['image'],
	['clean'],
	['undo'],
	['redo'],
];
		
var options = {
	modules: {
		toolbar: toolbarOptions,
		history
	},
	debug: 'error',
	theme: 'snow'
};
// 初始化编辑器
var quill = new Quill('#quill', options);

var toolbar = quill.getModule('toolbar');
// 选择图片
toolbar.addHandler('image', function() {
	document.getElementById('file').click();
});
// 发布
document.getElementById("release").onclick = function() {
	var content = quill.getContents();
	console.log(content);
	let html = quill.container.firstChild.innerHTML;
	console.log(html);
};
// 撤销
document.querySelector(".ql-undo").addEventListener('click', function() {
	quill.history.undo();
});
// 重做
document.querySelector(".ql-redo").addEventListener('click', function() {
	quill.history.redo();
});
```

另外一点需要注意的就是 `Quill` 提供的 `getContents` 方法。它返回的是一个 `Delta` `对象，表示编辑器的内容。Delta` 本质上是 `JSON`，可以非常方便的进行个性化处理。`
